In [1]:
import torch

In [2]:
tensor1 = torch.Tensor([[1, 2, 3],
                       [4, 5, 6]])
tensor1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [3]:
tensor2 = torch.Tensor([[7, 8, 9],
                       [10, 11, 12]])
tensor2

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

# requires_grad:
   When true, it keep tracks computations for a tensor in forward phase and calculate gradients for this tensor in backword phase.
   
   
   By default, it is false. To enable it, use requires_grad_() flag.

In [4]:
tensor1.requires_grad

False

In [5]:
tensor2.requires_grad

False

In [6]:
tensor1.requires_grad_()

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [7]:
tensor2.requires_grad_()

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]], requires_grad=True)

In [8]:
tensor1.requires_grad

True

In [9]:
print(tensor1.grad)

None


In [10]:
print(tensor1.grad_fn)

None


In [11]:
output_tensor = tensor1 * tensor2

In [12]:
output_tensor.requires_grad

True

In [13]:
print(output_tensor.grad)

None


<ipython-input-13-bf53a7edc26d>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(output_tensor.grad)


In [14]:
print(output_tensor.grad_fn)

In [15]:
output_tensor = (tensor1 * tensor2).mean()
print(output_tensor.grad_fn)

In [16]:
print(tensor1.grad)

None


In [17]:
output_tensor.backward()

In [18]:
print(tensor1.grad)

tensor([[1.1667, 1.3333, 1.5000],
        [1.6667, 1.8333, 2.0000]])


In [19]:
tensor1.grad.shape, tensor1.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [20]:
print(tensor2.grad)

tensor([[0.1667, 0.3333, 0.5000],
        [0.6667, 0.8333, 1.0000]])


In [21]:
print(output_tensor.grad)

None


<ipython-input-21-bf53a7edc26d>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(output_tensor.grad)


In [22]:
new_tensor = tensor1 * 3
print(new_tensor.requires_grad)

True


In [23]:
new_tensor

tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]], grad_fn=<MulBackward0>)

In [26]:
with torch.no_grad():
    
    new_tensor = tensor1 * 3 
    
    print('new_tensor = ', new_tensor)
    
    print('requires_grad for tensor = ', tensor1.requires_grad)
    
    print('requires_grad for tensor = ', tensor2.requires_grad)
    
    print('requires_grad for new tensor = ', new_tensor.requires_grad)

new_tensor =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]])
requires_grad for tensor =  True
requires_grad for tensor =  True
requires_grad for new tensor =  False


In [27]:
def calculate(t):
    return t * 2

In [28]:
@torch.no_grad()
def calculate_with_no_grad(t):
    return t * 2

In [29]:
result_tensor = calculate(tensor1)

result_tensor

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]], grad_fn=<MulBackward0>)

In [30]:
result_tensor.requires_grad

True

In [31]:
result_tensor_no_grad = calculate_with_no_grad(tensor1)

result_tensor_no_grad

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [32]:
result_tensor_no_grad.requires_grad

False

In [33]:
with torch.no_grad():
    
    new_tensor_no_grad = tensor1 *3
    
    print('new_tensor_no_grad = ', new_tensor_no_grad)
    
    with torch.enable_grad():
        
        new_tensor_grad = tensor1 * 3
        
        print('new_tensor_grad = ', new_tensor_grad)

new_tensor_no_grad =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]])
new_tensor_grad =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]], grad_fn=<MulBackward0>)


In [34]:
tensor_one = torch.tensor([[1.0, 2.0],
                           [3.0, 4.0]], requires_grad=True)
tensor_one

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [36]:
tensor_two = torch.Tensor([[5, 6],
                           [7, 8]])
tensor_two

tensor([[5., 6.],
        [7., 8.]])

In [40]:
tensor_one.requires_grad

True

In [43]:
tensor_two.requires_grad_()

tensor([[5., 6.],
        [7., 8.]], requires_grad=True)

In [45]:
final_tensor = (tensor_one + tensor_two).mean()
final_tensor

tensor(9., grad_fn=<MeanBackward0>)

In [47]:
final_tensor.requires_grad

True

In [48]:
print(tensor_one.grad)

None


In [49]:
print(tensor_two.grad)

None


In [50]:
final_tensor.backward()

In [51]:
print(tensor_one.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


In [52]:
print(tensor_two.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


In [53]:
detached_tensor = tensor_one.detach()

detached_tensor

tensor([[1., 2.],
        [3., 4.]])

In [54]:
tensor_one

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [55]:
mean_tensor = (tensor_one + detached_tensor).mean()

mean_tensor.backward()

In [56]:
tensor_one.grad

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])

In [58]:
print(detached_tensor.grad)

None
