In [1]:
import numpy as np
import torch

In [2]:
tensor = torch.rand(4, 3)
tensor

tensor([[0.7693, 0.5388, 0.0124],
        [0.7382, 0.5096, 0.7311],
        [0.4862, 0.9731, 0.6329],
        [0.4649, 0.0353, 0.1407]])

In [4]:
type(tensor)

torch.Tensor

In [5]:
# convert tensor to np array

numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([[0.769268  , 0.53881794, 0.01239169],
       [0.7381553 , 0.5096142 , 0.73108166],
       [0.4861979 , 0.9730961 , 0.6329091 ],
       [0.4649489 , 0.03532398, 0.14071745]], dtype=float32)

In [6]:
type(numpy_from_tensor)

numpy.ndarray

In [7]:
torch.is_tensor(tensor)

True

In [8]:
torch.is_tensor(numpy_from_tensor)

False

In [9]:
numpy_from_tensor[0, 0] = 100.0
numpy_from_tensor

array([[1.0000000e+02, 5.3881794e-01, 1.2391686e-02],
       [7.3815531e-01, 5.0961423e-01, 7.3108166e-01],
       [4.8619789e-01, 9.7309607e-01, 6.3290912e-01],
       [4.6494889e-01, 3.5323977e-02, 1.4071745e-01]], dtype=float32)

In [10]:
tensor

tensor([[1.0000e+02, 5.3882e-01, 1.2392e-02],
        [7.3816e-01, 5.0961e-01, 7.3108e-01],
        [4.8620e-01, 9.7310e-01, 6.3291e-01],
        [4.6495e-01, 3.5324e-02, 1.4072e-01]])

In [11]:
numpy_arr = np.array([[1.0, 2.0, 3.0],
                      [10.0, 20.0, 30.0],
                      [100.0, 200.0, 300.0]])

numpy_arr

array([[  1.,   2.,   3.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [12]:
# convert np array to tensor

tensor_from_numpy = torch.from_numpy(numpy_arr)
tensor_from_numpy

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [13]:
type(tensor_from_numpy)

torch.Tensor

In [14]:
torch.is_tensor(tensor_from_numpy)

True

In [15]:
tensor_from_numpy[0] = 1
tensor_from_numpy

tensor([[  1.,   1.,   1.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [16]:
numpy_arr

array([[  1.,   1.,   1.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [17]:
np_array_one = np.array([4, 8])
np_array_one

array([4, 8])

In [18]:
# to prevent unnecessary copy of tensor, if the input to as_tensor function is already a tensor

tensor_from_array_one = torch.as_tensor(np_array_one)
tensor_from_array_one

tensor([4, 8])

In [19]:
np_array_one[1] = 5
np_array_one

array([4, 5])

In [20]:
tensor_from_array_one

tensor([4, 5])

In [21]:
np_array_two = np.array([2, 2])
np_array_two

array([2, 2])

In [22]:
#here tensor is a copy of numpy array
tensor_from_array_two = torch.tensor(np_array_two)

tensor_from_array_two

tensor([2, 2])

In [23]:
np_array_two[1] = 4
np_array_two

array([2, 4])

In [24]:
tensor_from_array_two

tensor([2, 2])