In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
torch.cuda.init()

In [4]:
torch.cuda.current_device()

0

In [5]:
torch.cuda.device_count()

1

In [6]:
# how much memory, our tensors occupied

torch.cuda.memory_allocated()

0

In [8]:
# how much cache memory is allocated

# torch.cuda.memory_cached()
torch.cuda.memory_reserved()

0

In [9]:
cuda = torch.device('cuda')

cuda

device(type='cuda')

In [10]:
cuda0 = torch.device('cuda:0')
cuda1 = torch.device('cuda:1')
cuda2 = torch.device('cuda:2')

In [11]:
cuda0, cuda1, cuda2

(device(type='cuda', index=0),
 device(type='cuda', index=1),
 device(type='cuda', index=2))

In [12]:
x = torch.tensor([10., 20.])

x

tensor([10., 20.])

In [13]:
# initialize tensor on cuda device

x_default = torch.tensor([10., 20.0], device=cuda) 

x_default

tensor([10., 20.], device='cuda:0')

In [14]:
x0 = torch.tensor([10., 20.0], device=cuda0) 

x0

tensor([10., 20.], device='cuda:0')

In [15]:
x1 = torch.tensor([10., 20.0], device=cuda1) 

x1

RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

In [16]:
# create copy of a tensor
y = x.cuda()

y

tensor([10., 20.], device='cuda:0')

In [17]:
y0 = x1.cuda()

y0

NameError: name 'x1' is not defined

In [18]:
# To change the default cuda device

print('Outside with context: ', torch.cuda.current_device())

with torch.cuda.device(1):
    print('Inside the context: ', torch.cuda.current_device())
    
print('Outside the context again: ', torch.cuda.current_device())

Outside with context:  0


RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

In [19]:
with torch.cuda.device(1):
    
    a = torch.tensor([10., 20.])
    
    a0 = torch.tensor([10., 20.], device=cuda0)
    
    a1 = torch.tensor([10., 20.], device=cuda)

RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

In [20]:
a

NameError: name 'a' is not defined

In [21]:
a0

NameError: name 'a0' is not defined

In [22]:
a1

NameError: name 'a1' is not defined

In [23]:
# Tensor data-type or device conversion

b1 = a0.to(device=cuda1)

b1

NameError: name 'a0' is not defined

In [24]:
torch.cuda.memory_allocated()

1536

In [25]:
torch.cuda.memory_cached()

/home/neeraj/.local/lib/python3.8/site-packages/torch/cuda/memory.py:384: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(


2097152

In [26]:
torch.cuda.empty_cache()

In [27]:
torch.cuda.memory_cached()

/home/neeraj/.local/lib/python3.8/site-packages/torch/cuda/memory.py:384: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(


2097152

In [29]:
# create same data-type as original on the same device
preserve_context = x.new_full([2, 2], fill_value=1.1)

preserve_context

tensor([[1.1000, 1.1000],
        [1.1000, 1.1000]])

In [30]:
preserve_context0 = x0.new_full([2, 2], fill_value=1.1)

preserve_context0

tensor([[1.1000, 1.1000],
        [1.1000, 1.1000]], device='cuda:0')