In [1]:
import torch

print(torch.__version__)

1.8.1+cpu


In [2]:
# default data-type
torch.get_default_dtype()

torch.float32

In [3]:
# setting default data-type
torch.set_default_dtype(torch.int)

TypeError: only floating-point types are supported as the default type

In [4]:
torch.set_default_dtype(torch.float64)

In [5]:
torch.get_default_dtype()

torch.float64

In [6]:
# initialize a tensor
tensor_arr = torch.Tensor([[1,2,3],[4,5,6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [7]:
# to check, whether is it tensor or not
torch.is_tensor(tensor_arr)

True

In [8]:
# number of elements in tensor
torch.numel(tensor_arr)

6

In [9]:
# uninitialized a tensor of given size
tensor_uninitialized = torch.Tensor(2, 2)
tensor_uninitialized

tensor([[6.9185e-310, 4.6557e-310],
        [4.9407e-324,  0.0000e+00]])

In [10]:
# initialize a tensor with random values
tensor_initialized = torch.rand(2, 2)
tensor_initialized

tensor([[0.2741, 0.6995],
        [0.5481, 0.4172]])

In [11]:
# Initilaize a tensor of our type
tensor_int = torch.tensor([5, 3]).type(torch.IntTensor)
tensor_int

tensor([5, 3], dtype=torch.int32)

In [12]:
tensor_short = torch.ShortTensor([1.0, 2.0, 3.0])
tensor_short

<ipython-input-12-13d21c85b74a>:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  tensor_short = torch.ShortTensor([1.0, 2.0, 3.0])


tensor([1, 2, 3], dtype=torch.int16)

In [13]:
# Initiaize a tensor, which takes half-memory than flaot32
tensor_float = torch.tensor([1.0, 2.0, 3.0]).type(torch.half)
tensor_float

tensor([1., 2., 3.], dtype=torch.float16)

In [14]:
# tensor with a particular value for a given shape

tensor_fill = torch.full((2,6), fill_value=10)
tensor_fill

tensor([[10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10]])

In [15]:
# initialize a tensor with all ones
tensor_of_ones = torch.ones([2, 4], dtype=torch.int32)
tensor_of_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [16]:
# initialize a tensor with all zeros
tensor_of_zeros = torch.zeros_like(tensor_of_ones)
tensor_of_zeros

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [17]:
# initialize a tensor with 1 at diagonal positions and all others with 0  
tensor_eye  = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [18]:
# find indices at which tensor has non-zero value
non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [19]:
# copy of an existing tensor
i = torch.tensor([[0, 1, 1],
                 [2, 2, 0]])

In [20]:
v = torch.tensor([3, 4, 5], dtype=torch.float32)

In [21]:
# initialize sparse tensor
sparse_tensor = torch.sparse_coo_tensor(i, v, [2, 5])

In [22]:
sparse_tensor.data

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)

In [23]:
initial_tensor = torch.rand(2, 3)

initial_tensor

tensor([[0.1129, 0.8993, 0.6318],
        [0.7457, 0.1980, 0.8559]])

In [24]:
initial_tensor.fill_(10)

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [25]:
initial_tensor.fill(10)

AttributeError: 'Tensor' object has no attribute 'fill'

In [26]:
new_tensor = initial_tensor.add(5)
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [27]:
initial_tensor.add_(8)

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [28]:
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [29]:
new_tensor.sqrt_()

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [30]:
x = torch.linspace(start=0.1, end=10.0, steps=15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [31]:
# divide the tensors into given number of chunks
tensor_chunk = torch.chunk(x, 3, 0)
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [32]:
# concatenate the tensors
tensor1 = tensor_chunk[0]
tensor2 = tensor_chunk[1]
tensor3 = torch.tensor([3.0, 4.0, 5.0])

torch.cat((tensor1, tensor2, tensor3), 0)

tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

In [33]:
random_tensor = torch.Tensor([[10, 8, 30], [40, 5, 6], [12, 2, 2]])
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2.,  2.]])

In [34]:
random_tensor[0, 1]

tensor(8.)

In [35]:
random_tensor[:, 2]

tensor([30.,  6.,  2.])

In [36]:
random_tensor[:2, :2]

tensor([[10.,  8.],
        [40.,  5.]])

In [37]:
random_tensor.size()

torch.Size([3, 3])

In [49]:
resized_tensor = random_tensor.view(9)
resized_tensor

tensor([ 10.,   8.,  30.,  40.,   5.,   6.,  12.,   2., 100.])

In [50]:
resized_tensor.size()

torch.Size([9])

In [51]:
# original tensor and its view share the same underlying memory

random_tensor[2, 2] = 100.0
resized_tensor

tensor([ 10.,   8.,  30.,  40.,   5.,   6.,  12.,   2., 100.])

In [41]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [42]:
random_tensor.shape

torch.Size([3, 3])

In [43]:
tensor_unsqueeze = torch.unsqueeze(random_tensor, 0)
print(tensor_unsqueeze.shape)
tensor_unsqueeze

torch.Size([1, 3, 3])


tensor([[[ 10.,   8.,  30.],
         [ 40.,   5.,   6.],
         [ 12.,   2., 100.]]])

In [44]:
tensor_unsqueeze = torch.unsqueeze(random_tensor, 1)
print(tensor_unsqueeze.shape)
tensor_unsqueeze

torch.Size([3, 1, 3])


tensor([[[ 10.,   8.,  30.]],

        [[ 40.,   5.,   6.]],

        [[ 12.,   2., 100.]]])

In [45]:
tensor_unsqueeze = torch.unsqueeze(random_tensor, 2)
print(tensor_unsqueeze.shape)
tensor_unsqueeze

torch.Size([3, 3, 1])


tensor([[[ 10.],
         [  8.],
         [ 30.]],

        [[ 40.],
         [  5.],
         [  6.]],

        [[ 12.],
         [  2.],
         [100.]]])

In [46]:
tensor_unsqueeze = torch.unsqueeze(random_tensor, 3)
tensor_unsqueeze

IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

In [47]:
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [48]:
# Transpose of a tensor
tensor_transpose = torch.transpose(initial_tensor, 0, 1)
tensor_transpose

tensor([[18., 18.],
        [18., 18.],
        [18., 18.]])

## Elementwise and matrix Operations on Tensors

In [52]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [53]:
sorted_tensor, sorted_indices = torch.sort(random_tensor)

In [54]:
sorted_tensor

tensor([[  8.,  10.,  30.],
        [  5.,   6.,  40.],
        [  2.,  12., 100.]])

In [55]:
sorted_indices

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])

In [56]:
tensor_float = torch.FloatTensor([-1.1, -2.2, 3.3])
tensor_float

tensor([-1.1000, -2.2000,  3.3000], dtype=torch.float32)

In [57]:
tensor_abs = torch.abs(tensor_float)
tensor_abs

tensor([1.1000, 2.2000, 3.3000], dtype=torch.float32)

In [58]:
rand1 = torch.abs(torch.randn(2, 3))
rand2 = torch.abs(torch.randn(2, 3))

In [59]:
add1 = rand1 + rand2
add1

tensor([[0.8588, 2.2784, 1.1907],
        [0.9252, 1.2031, 1.2419]])

In [60]:
add2 = torch.add(rand1, rand2)
add2

tensor([[0.8588, 2.2784, 1.1907],
        [0.9252, 1.2031, 1.2419]])

In [61]:
tensor = torch.Tensor([[-1, -2, -3],
                       [ 1,  2,  3]])

In [62]:
tensor_div = torch.div(tensor, tensor + 0.3)
tensor_div

tensor([[1.4286, 1.1765, 1.1111],
        [0.7692, 0.8696, 0.9091]])

In [65]:
tensor_mul = torch.mul(tensor, tensor)
tensor_mul

tensor([[1., 4., 9.],
        [1., 4., 9.]])

In [66]:
tensor_clamp = torch.clamp(tensor, min= -0.2, max=2)
tensor_clamp

tensor([[-0.2000, -0.2000, -0.2000],
        [ 1.0000,  2.0000,  2.0000]])

In [68]:
t1 = torch.Tensor([1, 2])
t2 = torch.Tensor([10, 20])

In [69]:
dot_product = torch.dot(t1, t2)
dot_product

tensor(50.)

In [70]:
matrix = torch.Tensor([[1, 2, 3],
                       [4, 5, 6]])

vector = torch.Tensor([0, 1, 2])

In [71]:
matrix_vector = torch.mv(matrix, vector)
matrix_vector

tensor([ 8., 17.])

In [72]:
another_matrix = torch.Tensor([[10, 30],
                               [20, 0],
                               [0 , 50]])

In [73]:
matrix_mul = torch.mm(matrix, another_matrix)
matrix_mul

tensor([[ 50., 180.],
        [140., 420.]])

In [74]:
torch.argmax(matrix_mul, dim=1)

tensor([1, 1])

In [76]:
torch.argmax(matrix_mul, dim=0)

tensor([1, 1])

In [77]:
torch.argmin(matrix_mul, dim=1)

tensor([0, 0])

In [78]:
torch.argmin(matrix_mul, dim=0)

tensor([0, 0])

In [79]:
a = torch.randn(4, 4)
a

tensor([[-0.9160,  1.0029, -2.5541, -0.5167],
        [ 1.0117, -0.6891,  0.0339,  0.5142],
        [-1.1055, -0.1336,  0.9318,  1.2730],
        [ 0.4997, -0.1856, -2.1257,  1.2648]])

In [81]:
torch.argmax(a, dim=1)

tensor([1, 0, 3, 3])

In [82]:
torch.argmax(a, dim=0)

tensor([1, 0, 2, 2])